source 'https://github.com/CocoaPods/Specs.git'

target 'SYNFadingLabel', :exclusive => true do
  pod "SYNFadingLabel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SYNFadingLabel", :path => "../"

  
end
